# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a506ab444a70455f31c700f8cf9ef757ad7b2cec672f7a279f6ee74711c16f8e97daf656b022056994a827d9924f7cb0f36789234270b9fe919205bae949c4c0

test:
  secret_key_base: e28d5c26ba2f99df1e61921063b3b25003f804bcf3f79e947407a7e5c21001c864dbbd486cfe73bead608711a9077a21ef755c7f64ae76941047ea10a7b7c3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
